// default package
// Generated Nov 22, 2015 2:09:29 PM by Hibernate Tools 3.4.0.CR1
package org.jl.dao.to;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Departments generated by hbm2java
 */
@Entity
@Table(name = "DEPARTMENTS")
public class Departments implements java.io.Serializable {

	private int departmentId;
	private Employees employees;

	private String departmentName;

	private Set<Employees> employeeses = new HashSet<Employees>(0);

	public Departments() {
	}

	public Departments(int departmentId, String departmentName) {
		this.departmentId = departmentId;
		this.departmentName = departmentName;
	}

	public Departments(int departmentId, Employees employees,
			 String departmentName,
			 Set<Employees> employeeses) {
		this.departmentId = departmentId;
		this.employees = employees;
		
		this.departmentName = departmentName;
		
		this.employeeses = employeeses;
	}

	@Id
	@Column(name = "DEPARTMENT_ID", unique = true, nullable = false, precision = 4, scale = 0)
	public int getDepartmentId() {
		return this.departmentId;
	}

	public void setDepartmentId(int departmentId) {
		this.departmentId = departmentId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MANAGER_ID")
	public Employees getEmployees() {
		return this.employees;
	}

	public void setEmployees(Employees employees) {
		this.employees = employees;
	}

	
	@Column(name = "DEPARTMENT_NAME", nullable = false, length = 30)
	public String getDepartmentName() {
		return this.departmentName;
	}

	public void setDepartmentName(String departmentName) {
		this.departmentName = departmentName;
	}

	

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "departments")
	public Set<Employees> getEmployeeses() {
		return this.employeeses;
	}

	public void setEmployeeses(Set<Employees> employeeses) {
		this.employeeses = employeeses;
	}

}
